/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { ProfilesControllerSearchProfilesParams } from "../../types/schemas";

import { apiClient } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getProfiles = () => {
  const profilesControllerSearchProfiles = (
    params?: ProfilesControllerSearchProfilesParams,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      { url: `/profiles`, method: "GET", params },
      options,
    );
  };
  const profilesControllerGetProfile = (
    id: string,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>({ url: `/profiles/${id}`, method: "GET" }, options);
  };
  return { profilesControllerSearchProfiles, profilesControllerGetProfile };
};
export type ProfilesControllerSearchProfilesResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getProfiles>["profilesControllerSearchProfiles"]
    >
  >
>;
export type ProfilesControllerGetProfileResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getProfiles>["profilesControllerGetProfile"]>
  >
>;
