/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

export interface AccountResponseDto {
  /** Unique identifier of the user */
  id: string;
  /** Full name of the user */
  fullName: string;
  /** User email address */
  email: string;
}
