/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { MqttConnectionConfigDto } from "./mqttConnectionConfigDto";
import type { ZigbeeConnectionConfigDto } from "./zigbeeConnectionConfigDto";
import type { TuyaConnectionConfigDto } from "./tuyaConnectionConfigDto";

/**
 * Protocol-specific connection settings. The structure depends on the `protocol` field.
 */
export type CreateDeviceDtoConnectionConfig =
  | MqttConnectionConfigDto
  | ZigbeeConnectionConfigDto
  | TuyaConnectionConfigDto;
