/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { CreateDeviceDtoProtocol } from "./createDeviceDtoProtocol";
import type { CreateDeviceDtoConnectionConfig } from "./createDeviceDtoConnectionConfig";

export interface CreateDeviceDto {
  /** User-defined name for the device */
  name: string;
  /** Communication protocol of the device */
  protocol: CreateDeviceDtoProtocol;
  /** UUID of the device profile (template) */
  profileId: string;
  /** Unique hardware ID (Topic, MAC, DevID) */
  externalId: string;
  /** ID of the group this device belongs to */
  groupId?: string;
  /** Protocol-specific connection settings. The structure depends on the `protocol` field. */
  connectionConfig: CreateDeviceDtoConnectionConfig;
}
