/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

export interface DeviceResponseDto {
  id: string;
  name: string;
  externalId: string;
  profileId: string;
  protocol: string;
  userId: string;
  connectionConfig: string;
}
