/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

export interface DeviceGroupResponseDto {
  id: string;
  name: string;
  description?: string;
  createdAt: string;
  /** Total number of devices in this group */
  devicesCount: number;
}
