/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { DevicesControllerGetUserDevicesProtocol } from "./devicesControllerGetUserDevicesProtocol";

export type DevicesControllerGetUserDevicesParams = {
  /**
   * Номер страницы
   */
  page?: number;
  /**
   * Количество на странице
   */
  limit?: number;
  /**
   * Фильтр по протоколу
   */
  protocol?: DevicesControllerGetUserDevicesProtocol;
  /**
   * ID группы
   */
  groupId?: string;
};
