/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { MetricRange } from "./metricRange";

export interface GetDeviceStatsDto {
  /** Time window duration anchored to latest data */
  range?: MetricRange;
  /** Unique identifier of the target device */
  deviceId: string;
  /** Telemetry metric tag key stored in InfluxDB */
  metricName: string;
}
