/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserDevicesProtocol } from "./getUserDevicesProtocol";

export type GetUserDevicesParams = {
  /**
   * Номер страницы
   */
  page?: number;
  /**
   * Количество на странице
   */
  limit?: number;
  /**
   * Фильтр по протоколу
   */
  protocol?: GetUserDevicesProtocol;
  /**
   * ID группы
   */
  groupId?: string;
};
