/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { AccountResponseDto } from "./accountResponseDto";

export interface LoginResponseDto {
  /** User account details */
  account: AccountResponseDto;
  /** JWT Access Token (short-lived) */
  accessToken: string;
  /** Refresh Token (long-lived, used to renew access token) */
  refreshToken: string;
}
