/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

/**
 * Time window duration anchored to latest data
 */
export type MetricRange = (typeof MetricRange)[keyof typeof MetricRange];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MetricRange = {
  "15m": "15m",
  "1h": "1h",
  "6h": "6h",
  "24h": "24h",
  "7d": "7d",
} as const;
