/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterAccountDto {
  /** @minLength 2 */
  fullName: string;
  email: string;
  /** @minLength 4 */
  password: string;
}
