/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

export type SearchProfilesProtocol =
  (typeof SearchProfilesProtocol)[keyof typeof SearchProfilesProtocol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchProfilesProtocol = {
  MQTT: "MQTT",
  ZIGBEE: "ZIGBEE",
  TUYA: "TUYA",
} as const;
