/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { SearchProfilesProtocol } from "./searchProfilesProtocol";

export type SearchProfilesParams = {
  /**
   * Search field (device name or vendor)
   */
  q?: string;
  /**
   * Filter by protocol
   */
  protocol?: SearchProfilesProtocol;
  limit?: number;
};
