/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { StatsResponseDtoValue } from "./statsResponseDtoValue";

export interface StatsResponseDto {
  timestamp: string;
  value: StatsResponseDtoValue;
}
