/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

export interface TuyaConnectionConfigDto {
  /** Product ID from Tuya Cloud */
  productId: string;
  /** User ID (uid) from Tuya Cloud context */
  uid?: string;
}
