/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

/**
 * New group ID for the device. Send `null` to remove from group.
 * @nullable
 */
export type UpdateDeviceDtoGroupId = { [key: string]: unknown } | null;
