/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

export interface ZigbeeConnectionConfigDto {
  /** MQTT prefix for Zigbee2MQTT (default: zigbee2mqtt) */
  topicPrefix?: string;
}
