/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateDeviceDto,
  DevicesControllerGetUserDevicesParams,
  UpdateDeviceDto,
} from "../../types/schemas";

import { apiClient } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getDevices = () => {
  const devicesControllerCreateDevice = (
    createDeviceDto: CreateDeviceDto,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      {
        url: `/devices`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createDeviceDto,
      },
      options,
    );
  };
  const devicesControllerUpdateDevice = (
    updateDeviceDto: UpdateDeviceDto,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      {
        url: `/devices`,
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        data: updateDeviceDto,
      },
      options,
    );
  };
  const devicesControllerGetUserDevices = (
    params?: DevicesControllerGetUserDevicesParams,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>({ url: `/devices`, method: "GET", params }, options);
  };
  const devicesControllerGetDevice = (
    id: string,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>({ url: `/devices/${id}`, method: "GET" }, options);
  };
  return {
    devicesControllerCreateDevice,
    devicesControllerUpdateDevice,
    devicesControllerGetUserDevices,
    devicesControllerGetDevice,
  };
};
export type DevicesControllerCreateDeviceResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDevices>["devicesControllerCreateDevice"]>
  >
>;
export type DevicesControllerUpdateDeviceResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDevices>["devicesControllerUpdateDevice"]>
  >
>;
export type DevicesControllerGetUserDevicesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDevices>["devicesControllerGetUserDevices"]>
  >
>;
export type DevicesControllerGetDeviceResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getDevices>["devicesControllerGetDevice"]>
  >
>;
