/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

/**
 * Communication protocol of the device
 */
export type CreateDeviceDtoProtocol =
  (typeof CreateDeviceDtoProtocol)[keyof typeof CreateDeviceDtoProtocol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateDeviceDtoProtocol = {
  MQTT: "MQTT",
  ZIGBEE: "ZIGBEE",
  TUYA: "TUYA",
} as const;
