/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

export interface MqttConnectionConfigDto {
  /** Topic for sending commands */
  commandTopic: string;
  /** Topic for receiving state updates */
  stateTopic: string;
}
