/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateDeviceDtoGroupId } from "./updateDeviceDtoGroupId";

export interface UpdateDeviceDto {
  /** device id */
  id: string;
  /** Id of device owner, for validation */
  userId: string;
  /** New name for the device */
  name?: string;
  /**
   * New group ID for the device. Send `null` to remove from group.
   * @nullable
   */
  groupId?: UpdateDeviceDtoGroupId;
}
