/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateGroupDto {
  /** The name of the group (e.g., room name) */
  name?: string;
  /** Optional description of the group */
  description?: string;
}
