/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */

export interface ZigbeeConnectionConfigDto {
  /** User-friendly name from Zigbee2MQTT */
  friendlyName: string;
}
