/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateGroupDto,
  DeviceGroupResponseDto,
  UpdateGroupDto,
} from "../../types/schemas";

import { apiClient } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getGroupsRooms = () => {
  /**
   * @summary Create a new device group
   */
  const groupsControllerCreate = (
    createGroupDto: CreateGroupDto,
    options?: SecondParameter<typeof apiClient<DeviceGroupResponseDto>>,
  ) => {
    return apiClient<DeviceGroupResponseDto>(
      {
        url: `/groups`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: createGroupDto,
      },
      options,
    );
  };
  /**
   * @summary Get list of user groups
   */
  const groupsControllerFindAll = (
    options?: SecondParameter<typeof apiClient<DeviceGroupResponseDto[]>>,
  ) => {
    return apiClient<DeviceGroupResponseDto[]>(
      { url: `/groups`, method: "GET" },
      options,
    );
  };
  /**
   * @summary Get group details
   */
  const groupsControllerFindOne = (
    id: string,
    options?: SecondParameter<typeof apiClient<DeviceGroupResponseDto>>,
  ) => {
    return apiClient<DeviceGroupResponseDto>(
      { url: `/groups/${id}`, method: "GET" },
      options,
    );
  };
  /**
   * @summary Update group details
   */
  const groupsControllerUpdate = (
    id: string,
    updateGroupDto: UpdateGroupDto,
    options?: SecondParameter<typeof apiClient<DeviceGroupResponseDto>>,
  ) => {
    return apiClient<DeviceGroupResponseDto>(
      {
        url: `/groups/${id}`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: updateGroupDto,
      },
      options,
    );
  };
  /**
   * @summary Delete group
   */
  const groupsControllerRemove = (
    id: string,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>({ url: `/groups/${id}`, method: "DELETE" }, options);
  };
  return {
    groupsControllerCreate,
    groupsControllerFindAll,
    groupsControllerFindOne,
    groupsControllerUpdate,
    groupsControllerRemove,
  };
};
export type GroupsControllerCreateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getGroupsRooms>["groupsControllerCreate"]>
  >
>;
export type GroupsControllerFindAllResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getGroupsRooms>["groupsControllerFindAll"]>
  >
>;
export type GroupsControllerFindOneResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getGroupsRooms>["groupsControllerFindOne"]>
  >
>;
export type GroupsControllerUpdateResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getGroupsRooms>["groupsControllerUpdate"]>
  >
>;
export type GroupsControllerRemoveResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getGroupsRooms>["groupsControllerRemove"]>
  >
>;
