/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AccountResponseDto,
  CredentialsLoginDto,
  GoogleLoginDto,
  LoginResponseDto,
  LogoutDto,
  RefreshTokensDto,
  RefreshTokensResponseDto,
  RegisterAccountDto,
} from "../schemas";

import { apiClient } from "../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Register a new account with email and password
 */
export const credentialsRegister = (
  registerAccountDto: RegisterAccountDto,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<void>(
    {
      url: `/auth/credentials/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: registerAccountDto,
      signal,
    },
    options,
  );
};

export const getCredentialsRegisterMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof credentialsRegister>>,
    TError,
    { data: RegisterAccountDto },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof credentialsRegister>>,
  TError,
  { data: RegisterAccountDto },
  TContext
> => {
  const mutationKey = ["credentialsRegister"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof credentialsRegister>>,
    { data: RegisterAccountDto }
  > = (props) => {
    const { data } = props ?? {};

    return credentialsRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CredentialsRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof credentialsRegister>>
>;
export type CredentialsRegisterMutationBody = RegisterAccountDto;
export type CredentialsRegisterMutationError = unknown;

/**
 * @summary Register a new account with email and password
 */
export const useCredentialsRegister = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof credentialsRegister>>,
      TError,
      { data: RegisterAccountDto },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof credentialsRegister>>,
  TError,
  { data: RegisterAccountDto },
  TContext
> => {
  const mutationOptions = getCredentialsRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Login with email and password
 */
export const credentialsLogin = (
  credentialsLoginDto: CredentialsLoginDto,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<LoginResponseDto>(
    {
      url: `/auth/credentials/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: credentialsLoginDto,
      signal,
    },
    options,
  );
};

export const getCredentialsLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof credentialsLogin>>,
    TError,
    { data: CredentialsLoginDto },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof credentialsLogin>>,
  TError,
  { data: CredentialsLoginDto },
  TContext
> => {
  const mutationKey = ["credentialsLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof credentialsLogin>>,
    { data: CredentialsLoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return credentialsLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CredentialsLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof credentialsLogin>>
>;
export type CredentialsLoginMutationBody = CredentialsLoginDto;
export type CredentialsLoginMutationError = unknown;

/**
 * @summary Login with email and password
 */
export const useCredentialsLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof credentialsLogin>>,
      TError,
      { data: CredentialsLoginDto },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof credentialsLogin>>,
  TError,
  { data: CredentialsLoginDto },
  TContext
> => {
  const mutationOptions = getCredentialsLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Login via Google OAuth2
 */
export const googleLogin = (
  googleLoginDto: GoogleLoginDto,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<LoginResponseDto>(
    {
      url: `/auth/google/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: googleLoginDto,
      signal,
    },
    options,
  );
};

export const getGoogleLoginMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof googleLogin>>,
    TError,
    { data: GoogleLoginDto },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof googleLogin>>,
  TError,
  { data: GoogleLoginDto },
  TContext
> => {
  const mutationKey = ["googleLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof googleLogin>>,
    { data: GoogleLoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return googleLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GoogleLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof googleLogin>>
>;
export type GoogleLoginMutationBody = GoogleLoginDto;
export type GoogleLoginMutationError = unknown;

/**
 * @summary Login via Google OAuth2
 */
export const useGoogleLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof googleLogin>>,
      TError,
      { data: GoogleLoginDto },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof googleLogin>>,
  TError,
  { data: GoogleLoginDto },
  TContext
> => {
  const mutationOptions = getGoogleLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Logout from the system
 */
export const logout = (
  logoutDto: LogoutDto,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<void>(
    {
      url: `/auth/logout`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: logoutDto,
      signal,
    },
    options,
  );
};

export const getLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    { data: LogoutDto },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logout>>,
  TError,
  { data: LogoutDto },
  TContext
> => {
  const mutationKey = ["logout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logout>>,
    { data: LogoutDto }
  > = (props) => {
    const { data } = props ?? {};

    return logout(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof logout>>
>;
export type LogoutMutationBody = LogoutDto;
export type LogoutMutationError = unknown;

/**
 * @summary Logout from the system
 */
export const useLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof logout>>,
      TError,
      { data: LogoutDto },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof logout>>,
  TError,
  { data: LogoutDto },
  TContext
> => {
  const mutationOptions = getLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Refresh access and refresh tokens
 */
export const refreshTokens = (
  refreshTokensDto: RefreshTokensDto,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<RefreshTokensResponseDto>(
    {
      url: `/auth/refresh-tokens`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: refreshTokensDto,
      signal,
    },
    options,
  );
};

export const getRefreshTokensMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof refreshTokens>>,
    TError,
    { data: RefreshTokensDto },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof refreshTokens>>,
  TError,
  { data: RefreshTokensDto },
  TContext
> => {
  const mutationKey = ["refreshTokens"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof refreshTokens>>,
    { data: RefreshTokensDto }
  > = (props) => {
    const { data } = props ?? {};

    return refreshTokens(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RefreshTokensMutationResult = NonNullable<
  Awaited<ReturnType<typeof refreshTokens>>
>;
export type RefreshTokensMutationBody = RefreshTokensDto;
export type RefreshTokensMutationError = unknown;

/**
 * @summary Refresh access and refresh tokens
 */
export const useRefreshTokens = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof refreshTokens>>,
      TError,
      { data: RefreshTokensDto },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof refreshTokens>>,
  TError,
  { data: RefreshTokensDto },
  TContext
> => {
  const mutationOptions = getRefreshTokensMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get current user account info
 */
export const getAccountInfo = (
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<AccountResponseDto>(
    { url: `/auth/account-info`, method: "GET", signal },
    options,
  );
};

export const getGetAccountInfoQueryKey = () => {
  return [`/auth/account-info`] as const;
};

export const getGetAccountInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getAccountInfo>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAccountInfo>>, TError, TData>
  >;
  request?: SecondParameter<typeof apiClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAccountInfoQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccountInfo>>> = ({
    signal,
  }) => getAccountInfo(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAccountInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAccountInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountInfo>>
>;
export type GetAccountInfoQueryError = unknown;

export function useGetAccountInfo<
  TData = Awaited<ReturnType<typeof getAccountInfo>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAccountInfo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccountInfo>>,
          TError,
          Awaited<ReturnType<typeof getAccountInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAccountInfo<
  TData = Awaited<ReturnType<typeof getAccountInfo>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAccountInfo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccountInfo>>,
          TError,
          Awaited<ReturnType<typeof getAccountInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAccountInfo<
  TData = Awaited<ReturnType<typeof getAccountInfo>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAccountInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user account info
 */

export function useGetAccountInfo<
  TData = Awaited<ReturnType<typeof getAccountInfo>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAccountInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAccountInfoQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
