/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * @summary Create a new device
 */
export const createDeviceBody = zod.object({
  "name": zod.string().describe('User-defined name for the device'),
  "protocol": zod.enum(['MQTT', 'ZIGBEE', 'TUYA']).describe('Communication protocol of the device'),
  "profileId": zod.string().describe('UUID of the device profile (template)'),
  "externalId": zod.string().describe('Unique hardware ID (Topic, MAC, DevID)'),
  "groupId": zod.string().optional().describe('ID of the group this device belongs to'),
  "connectionConfig": zod.union([zod.object({
  "stateTopic": zod.string().describe('Topic for receiving state updates'),
  "commandTopic": zod.string().optional().describe('Topic for sending commands (optional)')
}),zod.object({
  "topicPrefix": zod.string().optional().describe('MQTT prefix for Zigbee2MQTT (default: zigbee2mqtt)')
}),zod.object({
  "productId": zod.string().describe('Product ID from Tuya Cloud'),
  "uid": zod.string().optional().describe('User ID (uid) from Tuya Cloud context')
})]).describe('Protocol-specific connection settings. The structure depends on the `protocol` field.')
})

/**
 * @summary Update a device record
 */
export const updateDeviceBody = zod.object({
  "id": zod.string().describe('device id'),
  "userId": zod.string().describe('Id of device owner, for validation'),
  "name": zod.string().optional().describe('New name for the device'),
  "groupId": zod.object({

}).nullish().describe('New group ID for the device. Send `null` to remove from group.')
})

/**
 * @summary get all devices of authorithed user
 */
export const getUserDevicesQueryPageDefault = 1;export const getUserDevicesQueryLimitDefault = 10;

export const getUserDevicesQueryParams = zod.object({
  "page": zod.number().default(getUserDevicesQueryPageDefault).describe('Номер страницы'),
  "limit": zod.number().default(getUserDevicesQueryLimitDefault).describe('Количество на странице'),
  "protocol": zod.enum(['MQTT', 'ZIGBEE', 'TUYA']).optional().describe('Фильтр по протоколу'),
  "groupId": zod.string().optional().describe('ID группы')
})

/**
 * @summary Request device by id
 */
export const getDeviceParams = zod.object({
  "id": zod.string()
})

