/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateDeviceDto,
  GetUserDevicesParams,
  UpdateDeviceDto,
} from "../schemas";

import { apiClient } from "../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a new device
 */
export const createDevice = (
  createDeviceDto: CreateDeviceDto,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<void>(
    {
      url: `/devices`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createDeviceDto,
      signal,
    },
    options,
  );
};

export const getCreateDeviceMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDevice>>,
    TError,
    { data: CreateDeviceDto },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDevice>>,
  TError,
  { data: CreateDeviceDto },
  TContext
> => {
  const mutationKey = ["createDevice"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDevice>>,
    { data: CreateDeviceDto }
  > = (props) => {
    const { data } = props ?? {};

    return createDevice(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateDeviceMutationResult = NonNullable<
  Awaited<ReturnType<typeof createDevice>>
>;
export type CreateDeviceMutationBody = CreateDeviceDto;
export type CreateDeviceMutationError = unknown;

/**
 * @summary Create a new device
 */
export const useCreateDevice = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createDevice>>,
      TError,
      { data: CreateDeviceDto },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createDevice>>,
  TError,
  { data: CreateDeviceDto },
  TContext
> => {
  const mutationOptions = getCreateDeviceMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Update a device record
 */
export const updateDevice = (
  updateDeviceDto: UpdateDeviceDto,
  options?: SecondParameter<typeof apiClient>,
) => {
  return apiClient<void>(
    {
      url: `/devices`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateDeviceDto,
    },
    options,
  );
};

export const getUpdateDeviceMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDevice>>,
    TError,
    { data: UpdateDeviceDto },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDevice>>,
  TError,
  { data: UpdateDeviceDto },
  TContext
> => {
  const mutationKey = ["updateDevice"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDevice>>,
    { data: UpdateDeviceDto }
  > = (props) => {
    const { data } = props ?? {};

    return updateDevice(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateDeviceMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateDevice>>
>;
export type UpdateDeviceMutationBody = UpdateDeviceDto;
export type UpdateDeviceMutationError = unknown;

/**
 * @summary Update a device record
 */
export const useUpdateDevice = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateDevice>>,
      TError,
      { data: UpdateDeviceDto },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateDevice>>,
  TError,
  { data: UpdateDeviceDto },
  TContext
> => {
  const mutationOptions = getUpdateDeviceMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary get all devices of authorithed user
 */
export const getUserDevices = (
  params?: GetUserDevicesParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<void>(
    { url: `/devices`, method: "GET", params, signal },
    options,
  );
};

export const getGetUserDevicesQueryKey = (params?: GetUserDevicesParams) => {
  return [`/devices`, ...(params ? [params] : [])] as const;
};

export const getGetUserDevicesQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserDevices>>,
  TError = unknown,
>(
  params?: GetUserDevicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserDevices>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserDevicesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserDevices>>> = ({
    signal,
  }) => getUserDevices(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserDevices>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserDevicesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserDevices>>
>;
export type GetUserDevicesQueryError = unknown;

export function useGetUserDevices<
  TData = Awaited<ReturnType<typeof getUserDevices>>,
  TError = unknown,
>(
  params: undefined | GetUserDevicesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserDevices>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserDevices>>,
          TError,
          Awaited<ReturnType<typeof getUserDevices>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserDevices<
  TData = Awaited<ReturnType<typeof getUserDevices>>,
  TError = unknown,
>(
  params?: GetUserDevicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserDevices>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserDevices>>,
          TError,
          Awaited<ReturnType<typeof getUserDevices>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserDevices<
  TData = Awaited<ReturnType<typeof getUserDevices>>,
  TError = unknown,
>(
  params?: GetUserDevicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserDevices>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary get all devices of authorithed user
 */

export function useGetUserDevices<
  TData = Awaited<ReturnType<typeof getUserDevices>>,
  TError = unknown,
>(
  params?: GetUserDevicesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserDevices>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserDevicesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Request device by id
 */
export const getDevice = (
  id: string,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<void>(
    { url: `/devices/${id}`, method: "GET", signal },
    options,
  );
};

export const getGetDeviceQueryKey = (id?: string) => {
  return [`/devices/${id}`] as const;
};

export const getGetDeviceQueryOptions = <
  TData = Awaited<ReturnType<typeof getDevice>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDeviceQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDevice>>> = ({
    signal,
  }) => getDevice(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetDeviceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDevice>>
>;
export type GetDeviceQueryError = unknown;

export function useGetDevice<
  TData = Awaited<ReturnType<typeof getDevice>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDevice>>,
          TError,
          Awaited<ReturnType<typeof getDevice>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevice<
  TData = Awaited<ReturnType<typeof getDevice>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDevice>>,
          TError,
          Awaited<ReturnType<typeof getDevice>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDevice<
  TData = Awaited<ReturnType<typeof getDevice>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Request device by id
 */

export function useGetDevice<
  TData = Awaited<ReturnType<typeof getDevice>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDevice>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDeviceQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
