/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateGroupDto,
  DeviceGroupResponseDto,
  UpdateGroupDto,
} from "../schemas";

import { apiClient } from "../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create a new device group
 */
export const createGroup = (
  createGroupDto: CreateGroupDto,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<DeviceGroupResponseDto>(
    {
      url: `/groups`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createGroupDto,
      signal,
    },
    options,
  );
};

export const getCreateGroupMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createGroup>>,
    TError,
    { data: CreateGroupDto },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createGroup>>,
  TError,
  { data: CreateGroupDto },
  TContext
> => {
  const mutationKey = ["createGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createGroup>>,
    { data: CreateGroupDto }
  > = (props) => {
    const { data } = props ?? {};

    return createGroup(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof createGroup>>
>;
export type CreateGroupMutationBody = CreateGroupDto;
export type CreateGroupMutationError = unknown;

/**
 * @summary Create a new device group
 */
export const useCreateGroup = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createGroup>>,
      TError,
      { data: CreateGroupDto },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createGroup>>,
  TError,
  { data: CreateGroupDto },
  TContext
> => {
  const mutationOptions = getCreateGroupMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get list of user groups
 */
export const getUserGroups = (
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<DeviceGroupResponseDto[]>(
    { url: `/groups`, method: "GET", signal },
    options,
  );
};

export const getGetUserGroupsQueryKey = () => {
  return [`/groups`] as const;
};

export const getGetUserGroupsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserGroups>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getUserGroups>>, TError, TData>
  >;
  request?: SecondParameter<typeof apiClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserGroupsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserGroups>>> = ({
    signal,
  }) => getUserGroups(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserGroups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserGroupsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserGroups>>
>;
export type GetUserGroupsQueryError = unknown;

export function useGetUserGroups<
  TData = Awaited<ReturnType<typeof getUserGroups>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGroups>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserGroups>>,
          TError,
          Awaited<ReturnType<typeof getUserGroups>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserGroups<
  TData = Awaited<ReturnType<typeof getUserGroups>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGroups>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserGroups>>,
          TError,
          Awaited<ReturnType<typeof getUserGroups>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserGroups<
  TData = Awaited<ReturnType<typeof getUserGroups>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGroups>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get list of user groups
 */

export function useGetUserGroups<
  TData = Awaited<ReturnType<typeof getUserGroups>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserGroups>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserGroupsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get group details
 */
export const findGroup = (
  id: string,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<DeviceGroupResponseDto>(
    { url: `/groups/${id}`, method: "GET", signal },
    options,
  );
};

export const getFindGroupQueryKey = (id?: string) => {
  return [`/groups/${id}`] as const;
};

export const getFindGroupQueryOptions = <
  TData = Awaited<ReturnType<typeof findGroup>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findGroup>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFindGroupQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findGroup>>> = ({
    signal,
  }) => findGroup(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof findGroup>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FindGroupQueryResult = NonNullable<
  Awaited<ReturnType<typeof findGroup>>
>;
export type FindGroupQueryError = unknown;

export function useFindGroup<
  TData = Awaited<ReturnType<typeof findGroup>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findGroup>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findGroup>>,
          TError,
          Awaited<ReturnType<typeof findGroup>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindGroup<
  TData = Awaited<ReturnType<typeof findGroup>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findGroup>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findGroup>>,
          TError,
          Awaited<ReturnType<typeof findGroup>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFindGroup<
  TData = Awaited<ReturnType<typeof findGroup>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findGroup>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get group details
 */

export function useFindGroup<
  TData = Awaited<ReturnType<typeof findGroup>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof findGroup>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFindGroupQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update group details
 */
export const updateGroup = (
  id: string,
  updateGroupDto: UpdateGroupDto,
  options?: SecondParameter<typeof apiClient>,
) => {
  return apiClient<DeviceGroupResponseDto>(
    {
      url: `/groups/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateGroupDto,
    },
    options,
  );
};

export const getUpdateGroupMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateGroup>>,
    TError,
    { id: string; data: UpdateGroupDto },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateGroup>>,
  TError,
  { id: string; data: UpdateGroupDto },
  TContext
> => {
  const mutationKey = ["updateGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateGroup>>,
    { id: string; data: UpdateGroupDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateGroup(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateGroup>>
>;
export type UpdateGroupMutationBody = UpdateGroupDto;
export type UpdateGroupMutationError = unknown;

/**
 * @summary Update group details
 */
export const useUpdateGroup = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateGroup>>,
      TError,
      { id: string; data: UpdateGroupDto },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateGroup>>,
  TError,
  { id: string; data: UpdateGroupDto },
  TContext
> => {
  const mutationOptions = getUpdateGroupMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Delete group
 */
export const deleteGroup = (
  id: string,
  options?: SecondParameter<typeof apiClient>,
) => {
  return apiClient<void>({ url: `/groups/${id}`, method: "DELETE" }, options);
};

export const getDeleteGroupMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteGroup>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteGroup>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteGroup"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteGroup>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteGroup(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteGroupMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteGroup>>
>;

export type DeleteGroupMutationError = unknown;

/**
 * @summary Delete group
 */
export const useDeleteGroup = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteGroup>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteGroup>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDeleteGroupMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
