/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * @summary Create a new device group
 */
export const groupsControllerCreateBody = zod.object({
  "name": zod.string().describe('The name of the group (e.g., room name)'),
  "description": zod.string().optional().describe('Optional description of the group')
})

/**
 * @summary Get list of user groups
 */
export const groupsControllerFindAllResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "createdAt": zod.string().datetime({}),
  "devicesCount": zod.number().describe('Total number of devices in this group')
})
export const groupsControllerFindAllResponse = zod.array(groupsControllerFindAllResponseItem)

/**
 * @summary Get group details
 */
export const groupsControllerFindOneParams = zod.object({
  "id": zod.string()
})

export const groupsControllerFindOneResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "createdAt": zod.string().datetime({}),
  "devicesCount": zod.number().describe('Total number of devices in this group')
})

/**
 * @summary Update group details
 */
export const groupsControllerUpdateParams = zod.object({
  "id": zod.string()
})

export const groupsControllerUpdateBody = zod.object({
  "name": zod.string().optional().describe('The name of the group (e.g., room name)'),
  "description": zod.string().optional().describe('Optional description of the group')
})

export const groupsControllerUpdateResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "createdAt": zod.string().datetime({}),
  "devicesCount": zod.number().describe('Total number of devices in this group')
})

/**
 * @summary Delete group
 */
export const groupsControllerRemoveParams = zod.object({
  "id": zod.string()
})

