/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * @summary Create a new device group
 */
export const createGroupBody = zod.object({
  "name": zod.string().describe('The name of the group (e.g., room name)'),
  "description": zod.string().optional().describe('Optional description of the group')
})

/**
 * @summary Get list of user groups
 */
export const getUserGroupsResponseItem = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "createdAt": zod.iso.datetime({}),
  "devicesCount": zod.number().describe('Total number of devices in this group')
})
export const getUserGroupsResponse = zod.array(getUserGroupsResponseItem)

/**
 * @summary Get group details
 */
export const findGroupParams = zod.object({
  "id": zod.string()
})

export const findGroupResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "createdAt": zod.iso.datetime({}),
  "devicesCount": zod.number().describe('Total number of devices in this group')
})

/**
 * @summary Update group details
 */
export const updateGroupParams = zod.object({
  "id": zod.string()
})

export const updateGroupBody = zod.object({
  "name": zod.string().optional().describe('The name of the group (e.g., room name)'),
  "description": zod.string().optional().describe('Optional description of the group')
})

export const updateGroupResponse = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "createdAt": zod.iso.datetime({}),
  "devicesCount": zod.number().describe('Total number of devices in this group')
})

/**
 * @summary Delete group
 */
export const deleteGroupParams = zod.object({
  "id": zod.string()
})

