/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * @summary Search profiles
 */
export const searchProfilesQueryLimitDefault = 20;

export const searchProfilesQueryParams = zod.object({
  "q": zod.string().optional().describe('Search field (device name or vendor)'),
  "protocol": zod.enum(['MQTT', 'ZIGBEE', 'TUYA']).optional().describe('Filter by protocol'),
  "limit": zod.number().default(searchProfilesQueryLimitDefault)
})

/**
 * @summary Get the profile by id
 */
export const getProfileParams = zod.object({
  "id": zod.string()
})

