/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



export const profilesControllerSearchProfilesQueryLimitDefault = 20;

export const profilesControllerSearchProfilesQueryParams = zod.object({
  "q": zod.string().optional().describe('Search field (device name or vendor)'),
  "protocol": zod.enum(['MQTT', 'ZIGBEE', 'TUYA']).optional().describe('Filter by protocol'),
  "limit": zod.number().default(profilesControllerSearchProfilesQueryLimitDefault)
})

export const profilesControllerGetProfileParams = zod.object({
  "id": zod.string()
})

