/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * @summary Fetch device metrics for charts
 */
export const fetchDeviceStatsBodyRangeDefault = "6h";

export const fetchDeviceStatsBody = zod.object({
  "range": zod.enum(['15m', '1h', '6h', '24h', '7d']).describe('Time window duration anchored to latest data').default(fetchDeviceStatsBodyRangeDefault).describe('Time window duration anchored to latest data'),
  "deviceId": zod.uuid().describe('Unique identifier of the target device'),
  "metricName": zod.string().describe('Telemetry metric tag key stored in InfluxDB')
})

export const fetchDeviceStatsResponseItem = zod.object({
  "timestamp": zod.string(),
  "value": zod.union([zod.string(),zod.number()])
})
export const fetchDeviceStatsResponse = zod.array(fetchDeviceStatsResponseItem)

