/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';



/**
 * @summary Get telemetry history for a device
 */
export const getDeviceStatsParams = zod.object({
  "id": zod.string()
})

export const getDeviceStatsQueryParams = zod.object({
  "range": zod.string()
})

