/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { GetDeviceStatsParams } from "../schemas";

import { apiClient } from "../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get telemetry history for a device
 */
export const getDeviceStats = (
  id: string,
  params: GetDeviceStatsParams,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<void>(
    { url: `/stats/device/${id}`, method: "GET", params, signal },
    options,
  );
};

export const getGetDeviceStatsQueryKey = (
  id?: string,
  params?: GetDeviceStatsParams,
) => {
  return [`/stats/device/${id}`, ...(params ? [params] : [])] as const;
};

export const getGetDeviceStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getDeviceStats>>,
  TError = unknown,
>(
  id: string,
  params: GetDeviceStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDeviceStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetDeviceStatsQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeviceStats>>> = ({
    signal,
  }) => getDeviceStats(id, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getDeviceStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDeviceStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDeviceStats>>
>;
export type GetDeviceStatsQueryError = unknown;

export function useGetDeviceStats<
  TData = Awaited<ReturnType<typeof getDeviceStats>>,
  TError = unknown,
>(
  id: string,
  params: GetDeviceStatsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDeviceStats>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeviceStats>>,
          TError,
          Awaited<ReturnType<typeof getDeviceStats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDeviceStats<
  TData = Awaited<ReturnType<typeof getDeviceStats>>,
  TError = unknown,
>(
  id: string,
  params: GetDeviceStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDeviceStats>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeviceStats>>,
          TError,
          Awaited<ReturnType<typeof getDeviceStats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDeviceStats<
  TData = Awaited<ReturnType<typeof getDeviceStats>>,
  TError = unknown,
>(
  id: string,
  params: GetDeviceStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDeviceStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get telemetry history for a device
 */

export function useGetDeviceStats<
  TData = Awaited<ReturnType<typeof getDeviceStats>>,
  TError = unknown,
>(
  id: string,
  params: GetDeviceStatsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDeviceStats>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDeviceStatsQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
