/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type { GetDeviceStatsDto, StatsResponseDto } from "../schemas";

import { apiClient } from "../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Fetch device metrics for charts
 */
export const fetchDeviceStats = (
  getDeviceStatsDto: GetDeviceStatsDto,
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<StatsResponseDto[]>(
    {
      url: `/stats/device`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: getDeviceStatsDto,
      signal,
    },
    options,
  );
};

export const getFetchDeviceStatsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof fetchDeviceStats>>,
    TError,
    { data: GetDeviceStatsDto },
    TContext
  >;
  request?: SecondParameter<typeof apiClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof fetchDeviceStats>>,
  TError,
  { data: GetDeviceStatsDto },
  TContext
> => {
  const mutationKey = ["fetchDeviceStats"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof fetchDeviceStats>>,
    { data: GetDeviceStatsDto }
  > = (props) => {
    const { data } = props ?? {};

    return fetchDeviceStats(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FetchDeviceStatsMutationResult = NonNullable<
  Awaited<ReturnType<typeof fetchDeviceStats>>
>;
export type FetchDeviceStatsMutationBody = GetDeviceStatsDto;
export type FetchDeviceStatsMutationError = unknown;

/**
 * @summary Fetch device metrics for charts
 */
export const useFetchDeviceStats = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof fetchDeviceStats>>,
      TError,
      { data: GetDeviceStatsDto },
      TContext
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof fetchDeviceStats>>,
  TError,
  { data: GetDeviceStatsDto },
  TContext
> => {
  const mutationOptions = getFetchDeviceStatsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
