/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type { StatsControllerGetDeviceStatsParams } from "../schemas";

import { apiClient } from "../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getStatistics = () => {
  /**
   * @summary Get telemetry history for a device
   */
  const statsControllerGetDeviceStats = (
    id: string,
    params: StatsControllerGetDeviceStatsParams,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      { url: `/stats/device/${id}`, method: "GET", params },
      options,
    );
  };
  return { statsControllerGetDeviceStats };
};
export type StatsControllerGetDeviceStatsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getStatistics>["statsControllerGetDeviceStats"]
    >
  >
>;
