/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { apiClient } from "../client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const streamControllerStreamGlobalEvents = (
  options?: SecondParameter<typeof apiClient>,
  signal?: AbortSignal,
) => {
  return apiClient<void>(
    { url: `/stream/events`, method: "GET", signal },
    options,
  );
};

export const getStreamControllerStreamGlobalEventsQueryKey = () => {
  return [`/stream/events`] as const;
};

export const getStreamControllerStreamGlobalEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof apiClient>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getStreamControllerStreamGlobalEventsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>
  > = ({ signal }) =>
    streamControllerStreamGlobalEvents(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type StreamControllerStreamGlobalEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>
>;
export type StreamControllerStreamGlobalEventsQueryError = unknown;

export function useStreamControllerStreamGlobalEvents<
  TData = Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
          TError,
          Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStreamControllerStreamGlobalEvents<
  TData = Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
          TError,
          Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useStreamControllerStreamGlobalEvents<
  TData = Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useStreamControllerStreamGlobalEvents<
  TData = Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof streamControllerStreamGlobalEvents>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof apiClient>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getStreamControllerStreamGlobalEventsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
