/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type {
  CredentialsLoginDto,
  LogoutDto,
  RefreshTokensDto,
  RegisterAccountDto,
} from "../../types/schemas";

import { apiClient } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAuth = () => {
  const authControllerCredentialsRegister = (
    registerAccountDto: RegisterAccountDto,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      {
        url: `/auth/credentials/register`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: registerAccountDto,
      },
      options,
    );
  };
  const authControllerCredentialsLogin = (
    credentialsLoginDto: CredentialsLoginDto,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      {
        url: `/auth/credentials/login`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: credentialsLoginDto,
      },
      options,
    );
  };
  const authControllerLogout = (
    logoutDto: LogoutDto,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      {
        url: `/auth/logout`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: logoutDto,
      },
      options,
    );
  };
  const authControllerRefreshTokens = (
    refreshTokensDto: RefreshTokensDto,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      {
        url: `/auth/refresh-tokens`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: refreshTokensDto,
      },
      options,
    );
  };
  const authControllerTestProtectedRoute = (
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      { url: `/auth/test-protected-router`, method: "POST" },
      options,
    );
  };
  return {
    authControllerCredentialsRegister,
    authControllerCredentialsLogin,
    authControllerLogout,
    authControllerRefreshTokens,
    authControllerTestProtectedRoute,
  };
};
export type AuthControllerCredentialsRegisterResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAuth>["authControllerCredentialsRegister"]>
  >
>;
export type AuthControllerCredentialsLoginResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAuth>["authControllerCredentialsLogin"]>
  >
>;
export type AuthControllerLogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerLogout"]>>
>;
export type AuthControllerRefreshTokensResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerRefreshTokens"]>>
>;
export type AuthControllerTestProtectedRouteResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAuth>["authControllerTestProtectedRoute"]>
  >
>;
