/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * IoT API
 * The IoT API description
 * OpenAPI spec version: 1.0.0
 */
import type {
  AccountResponseDto,
  CredentialsLoginDto,
  GoogleLoginDto,
  LoginResponseDto,
  LogoutDto,
  RefreshTokensDto,
  RefreshTokensResponseDto,
  RegisterAccountDto,
} from "../../types/schemas";

import { apiClient } from "../../api/client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getAuth = () => {
  /**
   * @summary Register a new account with email and password
   */
  const authControllerCredentialsRegister = (
    registerAccountDto: RegisterAccountDto,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      {
        url: `/auth/credentials/register`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: registerAccountDto,
      },
      options,
    );
  };
  /**
   * @summary Login with email and password
   */
  const authControllerCredentialsLogin = (
    credentialsLoginDto: CredentialsLoginDto,
    options?: SecondParameter<typeof apiClient<LoginResponseDto>>,
  ) => {
    return apiClient<LoginResponseDto>(
      {
        url: `/auth/credentials/login`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: credentialsLoginDto,
      },
      options,
    );
  };
  /**
   * @summary Login via Google OAuth2
   */
  const authControllerGoogleLogin = (
    googleLoginDto: GoogleLoginDto,
    options?: SecondParameter<typeof apiClient<LoginResponseDto>>,
  ) => {
    return apiClient<LoginResponseDto>(
      {
        url: `/auth/google/login`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: googleLoginDto,
      },
      options,
    );
  };
  /**
   * @summary Logout from the system
   */
  const authControllerLogout = (
    logoutDto: LogoutDto,
    options?: SecondParameter<typeof apiClient<void>>,
  ) => {
    return apiClient<void>(
      {
        url: `/auth/logout`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: logoutDto,
      },
      options,
    );
  };
  /**
   * @summary Refresh access and refresh tokens
   */
  const authControllerRefreshTokens = (
    refreshTokensDto: RefreshTokensDto,
    options?: SecondParameter<typeof apiClient<RefreshTokensResponseDto>>,
  ) => {
    return apiClient<RefreshTokensResponseDto>(
      {
        url: `/auth/refresh-tokens`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: refreshTokensDto,
      },
      options,
    );
  };
  /**
   * @summary Get current user account info
   */
  const authControllerAccountInfo = (
    options?: SecondParameter<typeof apiClient<AccountResponseDto>>,
  ) => {
    return apiClient<AccountResponseDto>(
      { url: `/auth/account-info`, method: "GET" },
      options,
    );
  };
  return {
    authControllerCredentialsRegister,
    authControllerCredentialsLogin,
    authControllerGoogleLogin,
    authControllerLogout,
    authControllerRefreshTokens,
    authControllerAccountInfo,
  };
};
export type AuthControllerCredentialsRegisterResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAuth>["authControllerCredentialsRegister"]>
  >
>;
export type AuthControllerCredentialsLoginResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAuth>["authControllerCredentialsLogin"]>
  >
>;
export type AuthControllerGoogleLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerGoogleLogin"]>>
>;
export type AuthControllerLogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerLogout"]>>
>;
export type AuthControllerRefreshTokensResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerRefreshTokens"]>>
>;
export type AuthControllerAccountInfoResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authControllerAccountInfo"]>>
>;
